AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 instance for monitoring

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c55b159cbfafe1f0
